export enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  PROPERTY_NOT_FOUND = 'PROPERTY_NOT_FOUND',
  UNIT_NOT_FOUND = 'UNIT_NOT_FOUND',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  AGREEMENT_NOT_FOUND = 'AGREEMENT_NOT_FOUND',
  MONTHLY_RENT_NOT_FOUND = 'MONTHLY_RENT_NOT_FOUND',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  EXPENSE_NOT_FOUND = 'EXPENSE_NOT_FOUND',
  REMINDER_NOT_FOUND = 'REMINDER_NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  UNIT_ALREADY_OCCUPIED = 'UNIT_ALREADY_OCCUPIED',
  AGREEMENT_OVERLAP = 'AGREEMENT_OVERLAP',
  TENANT_ACTIVE_AGREEMENT_EXISTS = 'TENANT_ACTIVE_AGREEMENT_EXISTS',
  RENT_ALREADY_GENERATED = 'RENT_ALREADY_GENERATED',
  PAYMENT_EXCEEDS_REMAINING = 'PAYMENT_EXCEEDS_REMAINING',
  PAYMENT_ALREADY_REVERSED = 'PAYMENT_ALREADY_REVERSED',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  PROPERTY_ACCESS_DENIED = 'PROPERTY_ACCESS_DENIED',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_INVALID_MIME_TYPE = 'FILE_INVALID_MIME_TYPE',
  FILE_SIZE_EXCEEDED = 'FILE_SIZE_EXCEEDED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_ACCESS_DENIED = 'FILE_ACCESS_DENIED',
  FILE_NOT_IN_STORAGE = 'FILE_NOT_IN_STORAGE',
  SUPABASE_NOT_CONFIGURED = 'SUPABASE_NOT_CONFIGURED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export const BanglaMessages: Record<ErrorCode, string> = {
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 'ভুল ইমেইল/ফোন অথবা পাসওয়ার্ড।',
  [ErrorCode.AUTH_UNAUTHORIZED]: 'অনুমোদনহীন অ্যাক্সেস। অনুগ্রহ করে লগইন করুন।',
  [ErrorCode.AUTH_FORBIDDEN]: 'আপনার এই কাজটি করার অনুমতি নেই।',
  [ErrorCode.VALIDATION_ERROR]: 'অনুরোধের তথ্যে ভুল রয়েছে।',
  [ErrorCode.RESOURCE_NOT_FOUND]: 'তথ্য পাওয়া যায়নি।',
  [ErrorCode.PROPERTY_NOT_FOUND]: 'বাড়ি/সম্পত্তি পাওয়া যায়নি।',
  [ErrorCode.UNIT_NOT_FOUND]: 'ভাড়া ইউনিট পাওয়া যায়নি।',
  [ErrorCode.TENANT_NOT_FOUND]: 'ভাড়াটিয়া পাওয়া যায়নি।',
  [ErrorCode.AGREEMENT_NOT_FOUND]: 'ভাড়া চুক্তি পাওয়া যায়নি।',
  [ErrorCode.MONTHLY_RENT_NOT_FOUND]: 'মাসিক ভাড়ার হিসাব পাওয়া যায়নি।',
  [ErrorCode.PAYMENT_NOT_FOUND]: 'পেমেন্ট রেকর্ড পাওয়া যায়নি।',
  [ErrorCode.EXPENSE_NOT_FOUND]: 'খরচের হিসাব পাওয়া যায়নি।',
  [ErrorCode.REMINDER_NOT_FOUND]: 'রিমাইন্ডার পাওয়া যায়নি।',
  [ErrorCode.DUPLICATE_RESOURCE]: 'এই তথ্যটি ইতিমধ্যে বিদ্যমান রয়েছে।',
  [ErrorCode.UNIT_ALREADY_OCCUPIED]: 'এই ইউনিটটি ইতিমধ্যে ভাড়া দেওয়া হয়েছে।',
  [ErrorCode.AGREEMENT_OVERLAP]: 'এই ইউনিটে ইতিমধ্যে একটি সক্রিয় চুক্তি রয়েছে।',
  [ErrorCode.TENANT_ACTIVE_AGREEMENT_EXISTS]: 'এই ভাড়াটিয়ার ইতোমধ্যে একটি সক্রিয় ভাড়ার চুক্তি রয়েছে।',
  [ErrorCode.RENT_ALREADY_GENERATED]: 'এই মাসের ভাড়ার হিসাব ইতিমধ্যে তৈরি করা হয়েছে।',
  [ErrorCode.PAYMENT_EXCEEDS_REMAINING]: 'পেমেন্টের পরিমাণ বকেয়া পরিমাণের চেয়ে বেশি হতে পারে না।',
  [ErrorCode.PAYMENT_ALREADY_REVERSED]: 'এই পেমেন্টটি ইতিমধ্যে বাতিল (রিভার্স) করা হয়েছে।',
  [ErrorCode.INVALID_STATUS_TRANSITION]: 'অবস্থা পরিবর্তন সম্ভব নয়।',
  [ErrorCode.PROPERTY_ACCESS_DENIED]: 'এই সম্পত্তিতে আপনার অ্যাক্সেস নেই।',
  [ErrorCode.TENANT_ACCESS_DENIED]: 'এই ভাড়াটিয়ার তথ্যে আপনার অ্যাক্সেস নেই।',
  [ErrorCode.FILE_NOT_FOUND]: 'ফাইল পাওয়া যায়নি।',
  [ErrorCode.FILE_INVALID_MIME_TYPE]: 'এই ধরনের ফাইল আপলোড করা সম্ভব নয়।',
  [ErrorCode.FILE_SIZE_EXCEEDED]: 'ফাইলের আকার সীমা অতিক্রম করেছে।',
  [ErrorCode.FILE_UPLOAD_FAILED]: 'ফাইল আপলোড ব্যর্থ হয়েছে।',
  [ErrorCode.FILE_ACCESS_DENIED]: 'এই ফাইলে আপনার অ্যাক্সেস নেই।',
  [ErrorCode.FILE_NOT_IN_STORAGE]: 'ফাইলটি স্টোরেজে পাওয়া যায়নি। আপলোড সম্পন্ন হয়নি।',
  [ErrorCode.SUPABASE_NOT_CONFIGURED]: 'Supabase স্টোরেজ কনফিগার করা হয়নি।',
  [ErrorCode.INTERNAL_ERROR]: 'একটি অপ্রত্যাশিত সমস্যা হয়েছে। পুনরায় চেষ্টা করুন।',
};

export const EnglishMessages: Record<ErrorCode, string> = {
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 'Invalid email/phone or password.',
  [ErrorCode.AUTH_UNAUTHORIZED]: 'Unauthorized access. Please login.',
  [ErrorCode.AUTH_FORBIDDEN]: 'You do not have permission to perform this action.',
  [ErrorCode.VALIDATION_ERROR]: 'Request validation failed.',
  [ErrorCode.RESOURCE_NOT_FOUND]: 'Resource not found.',
  [ErrorCode.PROPERTY_NOT_FOUND]: 'Property not found.',
  [ErrorCode.UNIT_NOT_FOUND]: 'Unit not found.',
  [ErrorCode.TENANT_NOT_FOUND]: 'Tenant not found.',
  [ErrorCode.AGREEMENT_NOT_FOUND]: 'Rental agreement not found.',
  [ErrorCode.MONTHLY_RENT_NOT_FOUND]: 'Monthly rent record not found.',
  [ErrorCode.PAYMENT_NOT_FOUND]: 'Payment record not found.',
  [ErrorCode.EXPENSE_NOT_FOUND]: 'Expense record not found.',
  [ErrorCode.REMINDER_NOT_FOUND]: 'Reminder not found.',
  [ErrorCode.DUPLICATE_RESOURCE]: 'Resource already exists.',
  [ErrorCode.UNIT_ALREADY_OCCUPIED]: 'This unit is already occupied.',
  [ErrorCode.AGREEMENT_OVERLAP]: 'An active agreement already exists for this unit.',
  [ErrorCode.TENANT_ACTIVE_AGREEMENT_EXISTS]: 'This tenant already has an active rental agreement.',
  [ErrorCode.RENT_ALREADY_GENERATED]: 'Monthly rent for this period is already generated.',
  [ErrorCode.PAYMENT_EXCEEDS_REMAINING]: 'Payment amount cannot exceed the remaining balance.',
  [ErrorCode.PAYMENT_ALREADY_REVERSED]: 'This payment has already been reversed.',
  [ErrorCode.INVALID_STATUS_TRANSITION]: 'Invalid status transition.',
  [ErrorCode.PROPERTY_ACCESS_DENIED]: 'You do not have access to this property.',
  [ErrorCode.TENANT_ACCESS_DENIED]: 'You do not have access to this tenant.',
  [ErrorCode.FILE_NOT_FOUND]: 'File not found.',
  [ErrorCode.FILE_INVALID_MIME_TYPE]: 'This file type is not allowed.',
  [ErrorCode.FILE_SIZE_EXCEEDED]: 'File size exceeds the allowed limit.',
  [ErrorCode.FILE_UPLOAD_FAILED]: 'File upload failed.',
  [ErrorCode.FILE_ACCESS_DENIED]: 'You do not have access to this file.',
  [ErrorCode.FILE_NOT_IN_STORAGE]: 'File not found in storage. Upload may not have completed.',
  [ErrorCode.SUPABASE_NOT_CONFIGURED]: 'Supabase storage is not configured.',
  [ErrorCode.INTERNAL_ERROR]: 'An unexpected internal error occurred.',
};

export function getLocalizedMessage(code: ErrorCode | string, lang: string = 'bn'): string {
  const isEn = lang?.toLowerCase().startsWith('en');
  const dict = isEn ? EnglishMessages : BanglaMessages;
  return dict[code as ErrorCode] || (isEn ? 'An error occurred.' : 'একটি ত্রুটি ঘটেছে।');
}
